[tk.vars]

[tk.stores]
  [[store]]
    name="Keepass"
    path="trapper_keeper/secrets.kdbx"
    key="keepass/key.txt"
    token="keepass/keepass_token"
  [[store]]
    name="Properties"
    path="trapper_keeper/properties.sqlite"
  [[store]]
    name="StreamlitConfig"
    path="s"

